### PR TITLE
Disable Arma artillery computer

### PR DESCRIPTION
**Pull request by FakeMessiah27**
**When merged this pull request will:**
- Disable the Arma artillery computer. We were wondering for a while why the CBA setting for this didn't work, turns out there's a setting for it in the template as well. Shout out to Falk for finding it.

### CODE REVIEW

**Comment by Drofseh** [comment]
Why do you want to disable it? 

This was set intentionally because the mortars in our modpack do not function correctly with their range tables.
The artillery computer is, unfortunately, the only way to make accurate shots.

Unless the mods have fixed them then artillery computer should remain enabled.

**Comment by FakeMessiah27** [comment]
We discontinued player controlled mortars so there's no point. Meanwhile, any regular artillery piece or mortar gets the artillery computer, which is unrealistic for the time period.

**Comment by Drofseh** [comment]
Disabling the artillery computer will prevent us from using ANY of it though, as nothing has functional range tables right now.

I agree that the computer isn't realistic, but it's the best we've got if we want to use them at all.
I've even got a mission in mind for it.

**Comment by FakeMessiah27** [comment]
Hmm, fair enough I suppose, but we haven't used player controlled artillery in, well, years, with no intention of using a dedicated artillery crew anytime soon.

(That doesn't rule out the players happening across and then using an artillery piece for a bit though, if that's what you had in mind for you mission).

**Pull request closed without merging**
